name: Beyblade Stock Checker

on:
  repository_dispatch:
    types: [check_stock]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install playwright requests
          playwright install --with-deps chromium

      - name: Run Script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          TELEGRAM_GROUP_API_KEY: ${{ secrets.TELEGRAM_GROUP_API_KEY }}
        run: python check_beyblade.py
